Prices new
Hello-Go-Hard/Lab_python pull request #5
Opened 2020-02-10 12:03 UTC by Hello-Go-Hard

Work with csv files using only standard python libraries.

2020-02-13 16:10 UTC, MaksimDanilau requested changes

2020-02-13 16:10 UTC, MaksimDanilau commented on Prices.py
> +file.close()
один раз покажу, а ты проникнись и запомни:
```python
data = None
with open('prices.csv', 'r') as source:
    data = list(csv.DictReader(source))    
```

2020-02-13 18:46 UTC, Hello-Go-Hard commented on Prices.py
> +file.close()
Хорошо
Просто я их с прошлым в одно время кидал, по этому не исправил

2020-02-14 11:04 UTC, Hello-Go-Hard commented
Change username and add with

2020-02-17 12:43 UTC, MaksimDanilau approved these changes

2020-02-17 12:43 UTC, MaksimDanilau commented on Lab_python-prices/Prices.py
> +    file_output.close()
Ко всем записям в файл в коде тоже не мешало бы применить with statement

2020-02-17 12:43 UTC, MaksimDanilau commented on Lab_python-prices/Prices.py
> +print('Чай с индийскими специями')
шо це таке?

2020-02-17 12:45 UTC, Hello-Go-Hard commented on Lab_python-prices/Prices.py
> +print('Чай с индийскими специями')
Если про чай я просто забыл убрать свой лог

2020-02-17 12:50 UTC, MaksimDanilau commented
В целом хорошо, в будущем рекомендую почаще пользоваться with statement, это избавит от проблем)

С учётом того, что задача выполняется на одной машине, код написан не до конца оптимально - есть места, в которых несколько проходов по массиву можно схлопнуть в один, пожертвовав однострочными функциями

2020-02-17 12:52 UTC, Hello-Go-Hard commented on Lab_python-prices/Prices.py
> +print('Чай с индийскими специями')
Хорошо учту

2020-02-17 12:53 UTC, closed without merging